# Generated by Django 5.2.6 on 2025-09-14 13:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('gateway', models.CharField(choices=[('KHALTI', 'Khalti'), ('ESEWA', 'eSewa')], default='KHALTI', max_length=20)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='INITIATED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initial_khalti_id', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('khalti_status', models.CharField(blank=True, editable=False, max_length=50, null=True)),
                ('khalti_transaction_id', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('esewa_status', models.CharField(blank=True, editable=False, max_length=50, null=True)),
                ('esewa_reference_id', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('esewa_order_id', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
